export const departmentsData = {
  Managua: [
    "Ciudad Sandino",
    "El Crucero",
    "Managua",
    "Mateare",
    "San Francisco Libre",
    "San Rafael del Sur",
    "Ticuantepe",
    "Tipitapa",
    "Villa Carlos Fonseca",
  ],
  Masaya: [
    "Catarina",
    "La Concepción",
    "Masatepe",
    "Masaya",
    "Nandasmo",
    "Nindirí",
    "Niquinohomo",
    "San Juan de Oriente",
    "Tisma",
  ],
  León: [
    "Achuapa",
    "El Jicaral",
    "El Sauce",
    "La Paz Centro",
    "Larreynaga",
    "León",
    "Nagarote",
    "Quezalguaque",
    "Santa Rosa del Peñón",
    "Telica",
  ],
  Estelí: [
    "Condega",
    "Estelí",
    "La Trinidad",
    "Pueblo Nuevo",
    "San Juan de Limay",
    "San Nicolás",
  ],
  Chinandega: [
    "Chichigalpa",
    "Chinandega",
    "Cinco Pinos",
    "Corinto",
    "El Realejo",
    "El Viejo",
    "Posoltega",
    "Puerto Morazán",
    "San Francisco del Norte",
    "San Pedro del Norte",
    "Somotillo",
    "Villanueva",
  ],
  Matagalpa: [
    "Ciudad Darío",
    "El Tuma-La Dalia",
    "Esquipulas",
    "Matagalpa",
    "Matiguás",
    "Muy Muy",
    "Rancho Grande",
    "Río Blanco",
    "San Dionisio",
    "San Isidro",
    "San Ramón",
    "Sébaco",
    "Terrabona",
  ],
  Granada: ["Diriá", "Diriomo", "Granada", "Nandaime"],
  Carazo: [
    "Diriamba",
    "Dolores",
    "El Rosario",
    "Jinotepe",
    "La Conquista",
    "La Paz de Carazo",
    "San Marcos",
    "Santa Teresa",
  ],
  Boaco: [
    "Boaco",
    "Camoapa",
    "San José de los Remates",
    "San Lorenzo",
    "Santa Lucía",
    "Teustepe",
  ],
  Jinotega: [
    "El Cuá",
    "Jinotega",
    "La Concordia",
    "San José de Bocay",
    "San Rafael del Norte",
    "San Sebastián de Yalí",
    "Santa María de Pantasma",
    "Wiwilí de Jinotega",
  ],
  Madriz: [
    "Las Sabanas",
    "Palacagüina",
    "San José de Cusmapa",
    "San Juan de Río Coco",
    "San Lucas",
    "Somoto",
    "Telpaneca",
    "Totogalpa",
    "Yalagüina",
  ],
  Rivas: [
    "Altagracia",
    "Belén",
    "Buenos Aires",
    "Cárdenas",
    "Moyogalpa",
    "Potosí",
    "Rivas",
    "San Jorge",
    "San Juan del Sur",
    "Tola",
  ],
  Chontales: [
    "Acoyapa",
    "Comalapa",
    "Cuapa",
    "El Coral",
    "Juigalpa",
    "La Libertad",
    "San Francisco de Cuapa",
    "San Pedro de Lóvago",
    "Santo Domingo",
    "Santo Tomás",
    "Villa Sandino",
  ],
  "Nueva Segovia": [
    "Ciudad Antigua",
    "Dipilto",
    "El Jícaro",
    "Jalapa",
    "Macuelizo",
    "Mozonte",
    "Murra",
    "Ocotal",
    "Quilalí",
    "San Fernando",
    "Santa María",
    "Wiwilí de Nueva Segovia",
  ],
  RAAS: [
    "Bluefields",
    "Corn Island",
    "Desembocadura del Río Grande",
    "El Ayote",
    "El Rama",
    "El Tortuguero",
    "Kukra Hill",
    "La Cruz de Río Grande",
    "Laguna de Perlas",
    "Muelle de los Bueyes",
    "Nueva Guinea",
    "Paiwas",
  ],
  RAAN: [
    "Bilwi",
    "Bonanza",
    "Mulukukú",
    "Prinzapolka",
    "Puerto Cabezas",
    "Rosita",
    "Siuna",
    "Waslala",
    "Waspam",
  ],
};
